### ISSUE TITLE
提一个建议，关于配置文件绑定顺序的问题

### ISSUE THREAD

**Issue by lihengming** [drtrang/druid-spring-boot#3]
```
min-evictable-idle-time-millis: 100000
max-evictable-idle-time-millis: 200000
```
你好，例如有上面这种配置，会导致单元测试失败，因为使用动态绑定会按ASCII的顺序绑定配置属性，也就是说max 是先于 min执行的，这也是Druid官方Starter放弃动态绑定这种便捷方式的原因之一，如果你有更好的解决方案，可以探讨下。

**Comment by drtrang** [comment]
根据给出的配置编写测试用例，没有复现问题。

单数据源测试用例：[DevProfilesTests.java](https://github.com/drtrang/druid-spring-boot/blob/master/druid-spring-boot-samples/src/test/java/com/github/trang/druid/test/DevProfilesTests.java)
多数据源测试用例：[DynamicDevProfilesTests.java](https://github.com/drtrang/druid-spring-boot/blob/master/druid-spring-boot-samples/src/test/java/com/github/trang/druid/test/DynamicDevProfilesTests.java)

**Comment by lihengming** [comment]
@drtrang 
hi，我研究了下，原来你把```@ConfigurationProperties```放在了一个继承DruidDataSource的包装类上，使用```@Bean(initMethod = "init", destroyMethod = "close")```调用DruidDataSource.init()来初始化数据源，这样Spring Boot 绑定就是按照对象成员变量的顺序调用set方法了，这样即解决了该问题同时IDE提示也会覆盖DruidDataSource内所有成员变量，为你的这个思路点赞。
```java
@ConditionalOnMissingBean(DataSource.class)
@ConfigurationProperties(DRUID_DATA_SOURCE_PREFIX)//如果放在这里，则使用ConfigurationPropertiesBindingPostProcessor来绑定，会出现顺序的问题
@Bean(initMethod = "init", destroyMethod = "close")
public DruidDataSource dataSource() {
    log.debug("druid data-source init...");
    return new DruidParentDataSource() {};
}
```
```java
@ConfigurationProperties(DRUID_DATA_SOURCE_PREFIX)
public abstract class DruidParentDataSource extends DruidDataSource {
```
但是，多数据源就不行了，它们只能把```@ConfigurationProperties```放在 Bean 上面，这样绑定的时候不会按照对象成员变量的顺序调用set方法，而是按照ASCII的顺序来调用set方法我想这也是Spring Boot ```ConfigurationPropertiesBindingPostProcessor```的一个失误吧，像下面这种配置就会报错。
```yml
spring:
  profiles: dynamic-dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    druid:
      one:
        name: one
        min-evictable-idle-time-millis: 100000
        max-evictable-idle-time-millis: 200000
      two:
        name: two
        min-evictable-idle-time-millis: 100000
        max-evictable-idle-time-millis: 200000
```
```java
  @Bean
    @ConfigurationProperties("spring.datasource.druid.one")
    public DruidDataSource firstDataSource() {
        log.debug("druid first-data-source init...");
        return new DruidMultiDataSource();
    }

    @Bean
    @ConfigurationProperties("spring.datasource.druid.two")
    public DruidDataSource secondDataSource() {
        log.debug("druid second-data-source init...");
        return new DruidMultiDataSource();
    }
```

**Comment by drtrang** [comment]
直接上结论，导致 https://github.com/alibaba/druid/issues/1796 的原因在于 Spring Boot 在读取 `.yml` 时是有序的，而读取 `.properties` 文件时是无序的。所以如果需要依赖于配置顺序，建议使用 YAML 方式。

[YamlPropertySourceLoader#load(String name, Resource resource, String profile)](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/env/YamlPropertySourceLoader.java)
```java
// 用 LinkedHashMap 解析
public Map<String, Object> process() {
    final Map<String, Object> result = new LinkedHashMap<String, Object>();
    process(new MatchCallback() {
        @Override
        public void process(Properties properties, Map<String, Object> map) {
            result.putAll(getFlattenedMap(map));
        }
    });
    return result;
}
```

[PropertiesPropertySourceLoader#load(String name, Resource resource, String profile)](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/env/PropertiesPropertySourceLoader.java)
```java
// 用 HashTable 解析
public PropertySource<?> load(String name, Resource resource, String profile) throws IOException {
    if (profile == null) {
        Properties properties = PropertiesLoaderUtils.loadProperties(resource);
        if (!properties.isEmpty()) {
            return new PropertiesPropertySource(name, properties);
        }
    }
    return null;
}
```

RelaxedDataBinder 在进行数据绑定的时候，会依据 PropertySource 的顺序赋值，而 Properties 继承自 HashTable，本身是无序的，那么出现问题就不稀奇了。

所以问题不在于单数据源或多数据源，也不在于 `@ConfigurationProperties` 注解是标注在 `DruidDataSource` 还是 `DruidParentDataSource` ，而是因为 Spring 对不同文件类型的处理方式不同。

**Comment by drtrang** [comment]
DruidParentDataSource 类存在的目的是为了注入 `spring.datasource.druid` 的配置。
基于 Spring4 的特性，DruidMultiDataSource 在继承 DruidParentDataSource 的同时，也会继承这些配置，由此解决多数据源场景下相同配置重复定义的问题。

也就是说，以下两种方式是等价的：
```yaml
spring:
  datasource:
    druid:
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 25200000
      one:
        name: one
      two:
        name: two
---
spring:
  datasource:
    druid:
      one:
        name: one
        min-evictable-idle-time-millis: 1800000
        max-evictable-idle-time-millis: 25200000
      two:
        name: two
        min-evictable-idle-time-millis: 1800000
        max-evictable-idle-time-millis: 25200000
```

若子数据源有相同的配置时，会覆盖掉父数据源的值：
```yaml
spring:
  datasource:
    druid:
      max-active: 20
      one:
        name: one
        max-active: 50
      two:
        name: two
```
